env:
  NODE_ENV: development

image:
  repository: localhost:5000/edit-me
  pullPolicy: Always
  tag: "latest"

volumes:
  - name: src-sync
    hostPath:
      path: "/run/desktop/mnt/host/drive/path/to/src"
      type: Directory
volumeMounts:
  - name: src-sync
    mountPath: /usr/app

terminationGracePeriodSeconds: 10