env:
  NODE_ENV: development

image:
  registry: localhost:5000
  repository: edit-me
  pullPolicy: Always
  tag: "latest"

volumes:
  - name: src-sync
    hostPath:
      path: "/run/desktop/mnt/host/drive/path/to/src"
      type: Directory
  - name: dep-sync
    emptyDir: {}

volumeMounts:
  - name: src-sync
    mountPath: /usr/app
  - name: dep-sync
    mountPath: /usr/app/node_modules

initContainerClone:
  command:
    - cp
    - -dR
    - /usr/app/node_modules/.
    - /node_modules/
  volumeMounts:  
    - name: dep-sync
      mountPath: /node_modules

updateStrategy:
  type: Recreate

terminationGracePeriodSeconds: 10