name: Build and release app
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Parse chart data
      uses: CumulusDS/get-yaml-paths-action@v0.1.1
      id: versioning
      with:
        file: chart/Chart.yaml
        appName: name
        appVersion: appVersion
    
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: ${{ steps.versioning.outputs.appName }}
        tags: ${{ steps.versioning.outputs.appVersion }}
        registry: 'registry.internal.fninfo.dev'
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
      
    - name: Upload chart
      uses: fninfo/helm3-push-action@master
      env:
        SOURCE_DIR: '.'
        CHART_FOLDER: 'chart'
        CHARTMUSEUM_URL: 'https://charts.internal.fninfo.dev'
        CHARTMUSEUM_USER: ${{ secrets.USER }}
        CHARTMUSEUM_PASSWORD: ${{ secrets.PASSWORD }}
        FORCE: 'True'